---

###################### Sample info ######################

SAMPLE:
  SRR13190144:  DMSO_rep1
  SRR13190145:  DMSO_rep2
  SRR13190146:  DMSO_rep3
  SRR13190150:  SR0813_rep1
  SRR13190151:  SR0813_rep2
  SRR13190152:  SR0813_rep3





END: 
  - 1


SRA:
  - SRR13190144
  - SRR13190145
  - SRR13190146
  - SRR13190150
  - SRR13190151
  - SRR13190152


FASTQ_PREFIX:
  - DMSO_rep1
  - DMSO_rep2
  - DMSO_rep3
  - SR0813_rep1
  - SR0813_rep2
  - SR0813_rep3


###################### Reference info ######################


REFERENCE_LINK:
  GENOME: 
    - 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/GRCh38.primary_assembly.genome.fa.gz'
    - 'GRCh38.primary_assembly.genome.fa.gz'
    - 'GRCh38.primary_assembly.genome.fa'
  ANNOTATION: 
    - 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/gencode.v37.primary_assembly.annotation.gtf.gz'
    - 'gencode.v37.primary_assembly.annotation.gtf.gz'
    - 'gencode.v37.primary_assembly.annotation.gtf'
    - 'gencode.v37.transcripts.fa'

###################### Extra-setting info ######################

INDEX_STAR: "/home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/reference/star_index" # Assigns path to star indexing directory (ABSOLUTE PATH NEEDED due to a potential STAR error!)

INDEX_HISAT: "reference/hisat2_index/hisat2_index" # Assigns hisat2 index files (e.g.reference/hisat2_index/hisat2_index.1.ht2, reference/hisat2_index/hisat2_index.2.ht2, ...)



FASTQ_EXT: '.fastq.gz'

RCONFIG: 'config/config_single.R'

CONDA: "config/conda_r.yaml"
  




