
###################### Sample info ######################



SAMPLE:
  Untreated1: SRR8245176
  Untreated2: SRR8245177
  Untreated3: SRR8245178
  Treated1: SRR8245179
  Treated2: SRR8245180
  Treated3: SRR8245181


END: 
  - 1
  - 2




###################### Reference info ########################
REFERENCE:
  - 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/'
  - 'GRCh38.primary_assembly.genome.fa'
  - 'gencode.v37.primary_assembly.annotation.gtf'
  
# e.g. 
# Reference genome link: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/GRCh38.primary_assembly.genome.fa.gz
# Reference annotation (GTF) link: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/gencode.v37.primary_assembly.annotation.gtf.gz 

###################### Extra-setting info ######################

INDEX_STAR: "/home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/reference/star_index" # Assigns path to star indexing directory (ABSOLUTE PATH NEEDED due to a potential STAR error!)

INDEX_HISAT: "reference/hisat2_index/hisat2_index" # Assigns hisat2 index files (e.g.reference/hisat2_index/hisat2_index.1.ht2, reference/hisat2_index/hisat2_index.2.ht2, ...)



FASTQ_EXT: '.fastq.gz'

RCONFIG: 'config/config_single.R'

CONDA: "config/conda_r.yaml"
  




