
###################### Sample info ######################

SAMPLE:
  SRR8245176: Untreated1
  SRR8245177: Untreated2
  SRR8245179: Treated1
  SRR8245180: Treated2
  




FASTQ_LIST:
  - Untreated1_1
  - Untreated1_2
  - Untreated2_1
  - Untreated2_2
  - Treated1_1
  - Treated1_2
  - Treated2_1
  - Treated2_2
  

END: 
  - 1
  - 2


SRA:
  - SRR8245176
  - SRR8245177
  - SRR8245179
  - SRR8245180
  

FASTQ_PREFIX:
  - Untreated1
  - Untreated2
  - Treated1
  - Treated2
  


###################### Reference info ######################
  

REFERENCE_LINK:
  GENOME: 
    - 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/GRCh38.primary_assembly.genome.fa.gz'
    - 'GRCh38.primary_assembly.genome.fa.gz'
    - 'GRCh38.primary_assembly.genome.fa'
  ANNOTATION: 
    - 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/gencode.v37.primary_assembly.annotation.gtf.gz'
    - 'gencode.v37.primary_assembly.annotation.gtf.gz'
    - 'gencode.v37.primary_assembly.annotation.gtf'

###################### Extra-setting info ######################

INDEX_STAR: "/home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/reference/star_index" # Assigns path to star indexing directory (ABSOLUTE PATH NEEDED due to a potential STAR error!)

INDEX_HISAT: "reference/hisat2_index/hisat2_index" # Assigns hisat2 index files (e.g.reference/hisat2_index/hisat2_index.1.ht2, reference/hisat2_index/hisat2_index.2.ht2, ...)


THREADS: 8     # Assigns the number of threads

STAR_OUT: "star_output"  # Assigns STAR output directory

HISAT2_OUT: "hisat2_output"  # Assigns HISAT2 output directory


FASTQ_EXT: '.fastq.gz'
  
